name: React CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run lint (optional)
        run: npm run lint || echo 'No lint script found'

      - name: Run tests (optional)
        run: npm test || echo 'No test script found'

      - name: Build React App
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/

  deploy:
    runs-on: self-hosted
    needs: build-test

    steps:
      - name: Run deployment script on server
        run: ssh -o StrictHostKeyChecking=no rakesh@localhost "bash /home/rakesh/deploy.sh"
