# name: React CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18"

#       - name: Install dependencies
#         run: npm install

#       - name: Run lint (optional)
#         run: npm run lint || echo 'No lint script found'

#       - name: Run tests (optional)
#         run: npm test || echo 'No test script found'

#       - name: Build React app
#         run: npm run build

#       - name: Copy build files to Linux server
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           port: 22
#           source: "dist/*"
#           target: "/var/www/my-react-app"

#       - name: Restart Nginx to serve new build
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           port: 22
#           script: sudo systemctl restart nginx

name: React CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run lint (optional)
        run: npm run lint || echo 'No lint script found'

      - name: Run tests (optional)
        run: npm test || echo 'No test script found'

      - name: Build React App
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/
